# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buyer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# I'm a hacker,I hack stuff,I love God father,son and holy spirit but
# I'm always badly ruined by sin,please God,guide me,cause I surrender all unto you


import json
import os
import webbrowser
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import sys
import resources_rc
import monitor
import dateline
from PyQt5.QtWidgets import QMessageBox

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/dictionary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowFlag(Qt.FramelessWindowHint)
        Form.setStyleSheet("background-color: #424242;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 10, 111, 71))
        self.label.setStyleSheet("image: url(:/newPrefix/resources/dictionary.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 111, 20))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(42, 140, 231, 20))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(name)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 190, 231, 20))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.textChanged.connect(phone)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 270, 61, 31))
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255);"+
        "border-width:2px;"+
        "border-radius:15px;"+
        "border-style: outset;"+
        "padding: 8px;"+
        "font-family:MS Shell Dlg 2;"+
        "min-width: 50px;"+
        "max-height: 10px;"+
        "min-height: 14px;"+
        "font-size:12px;"+
        "color:#000000;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(takeInput)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 270, 61, 31))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255);"+
        "border-width:2px;"+
        "border-radius:15px;"+
        "border-style: outset;"+
        "padding: 8px;"+
        "font-family:MS Shell Dlg 2;"+
        "min-width: 50px;"+
        "max-height: 10px;"+
        "min-height: 14px;"+
        "font-size:12px;"+
        "color:#000000;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(exit)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 270, 61, 31))
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255);"+
        "border-width:2px;"+
        "border-radius:15px;"+
        "border-style: outset;"+
        "padding: 8px;"+
        "font-family:MS Shell Dlg 2;"+
        "min-width: 50px;"+
        "max-height: 10px;"+
        "min-height: 14px;"+
        "font-size:12px;"+
        "color:#000000;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(help)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)      

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Buy dictionary"))
        self.label_2.setText(_translate("Form", "Buy Dictionary"))
        self.lineEdit.setPlaceholderText(_translate("Form", "  Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "  Telephone Number"))
        self.pushButton.setText(_translate("Form", "Buy"))
        self.pushButton_2.setText(_translate("Form", "Skip"))
        self.pushButton_3.setText(_translate("Form", "Help"))  

def exit():
    dateline.timeline()
    sys.exit(0)

def name(text):
    notification = monitor.getNotice()
    username = text 
    telephone = monitor.getTele()
    key = monitor.getKey()
    monitor.createfile(notice=notification,user=username,telephon=telephone,code=key)

def phone(text):
    notification = monitor.getNotice()
    username = monitor.getUser()
    telephone = text
    key = monitor.getKey()
    monitor.createfile(notice=notification,user=username,telephon=telephone,code=key)

def takeInput(): 
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/dictionary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    panel = QtWidgets.QWidget()
    panel.setWindowIcon(icon)
    key = QtWidgets.QInputDialog.getText(panel, 'Approve', 'Enter the code sent to you') 

    notification = monitor.getNotice()
    username = monitor.getUser()
    telephone = monitor.getTele()
    codeX = key[0]
    if codeX[0] == 'M' and codeX[1] == 'D' and codeX[2] == 'c':
        monitor.createfile(notice=notification,user=username,telephon=telephone,code=codeX)
    else:
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/dictionary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        messagebox = QMessageBox()
        messagebox.setWindowIcon(icon)
        messagebox.setWindowTitle("Invalid code")
        messagebox.setIcon(QMessageBox.Information)
        messagebox.setText("Please enter a valid code!")
        messagebox.setStandardButtons(QMessageBox.Close) 
        messagebox.exec()  

def help():
    file = os.path.exists("buy.html")
    if file == True:
        webbrowser.open("buy.html")
    else:
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/dictionary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        messagebox = QMessageBox()
        messagebox.setWindowIcon(icon)
        messagebox.setWindowTitle("Error")
        messagebox.setIcon(QMessageBox.Information)
        messagebox.setText("File not found!")
        messagebox.setStandardButtons(QMessageBox.Close) 
        messagebox.exec()              

def main():
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())         